services:
  postgres:
    image: postgres:15.2
    container_name: evianda-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: evianda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/evianda
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 123
volumes:
  postgres-data: